# ======================================================================
# Gateway - HTTP listener
# ======================================================================
# Purpose: Creates a loadbalancer with HTTP listener
# 
#  
# Traffic Flow:
#
# Notes:
#   - The AWS LoadBalancer controller features (such as Security groups)
#     can be added as annotations 
#   - This gateway does not redirect http traffic to https
#  
#   
# ======================================================================
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: semoss-gateway
  namespace: semoss
spec:
  infrastructure:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      # creating an internal NLB
      service.beta.kubernetes.io/aws-load-balancer-internal: "false"
      # adding SG
      service.beta.kubernetes.io/aws-load-balancer-security-groups: "sg-xxxxx"
      # istio is the default gatewayclassName
  gatewayClassName: istio
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: Same