apiVersion: v1
kind: ConfigMap
metadata:
  name: semoss-nginx-sidecar-config
  namespace: semoss
data:
  nginx.conf: |
    pid /tmp/nginx.pid;
    events {}
    http {
      client_body_temp_path /tmp/client_body_temp;
      proxy_temp_path        /tmp/proxy_temp;
      fastcgi_temp_path      /tmp/fastcgi_temp;
      uwsgi_temp_path        /tmp/uwsgi_temp;
      scgi_temp_path         /tmp/scgi_temp;
      server {
        listen 80;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
        location / {
          proxy_pass http://localhost:8080;
          proxy_cookie_path ~*^/.* /;
          proxy_read_timeout 350s;
          proxy_send_timeout 350s;
        }
      }
    }